# Generated by Django 3.2.8 on 2022-03-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0002_remove_benchmark_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benchmark',
            name='quote_currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='current_price',
        ),
    ]
